services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/api/node_modules
    depends_on:
      - db
  db:
    build:
      context: db
    container_name: db
    restart: always
    volumes:
      - ./db/volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: db/.env
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    env_file: frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - backend
